name = "meridian-ai-worker"
main = "src/index.ts"
compatibility_date = "2025-05-20"
compatibility_flags = ["nodejs_compat"]


[vars]
ENVIRONMENT = "dev"
LOG_LEVEL = "info"
AI_GATEWAY_URL = "https://gateway.ai.cloudflare.com/v1/c8317cfcb330d45b37b00ccd7e8a9936/meridian-ai"
AI_GATEWAY_TOKEN = "W-wyAUkVBh6qMzn_q5ayOurxjeQ2XYJKtQZo4AWk"
AI_GATEWAY_ACCOUNT_ID = "c8317cfcb330d45b37b00ccd7e8a9936"
AI_GATEWAY_NAME = "meridian-ai"

# 绑定 Cloudflare A
[ai]
binding = "AI"

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true


# 定义自定义域名
[env.production]
routes = [
  { pattern = "ai-worker.meridian.example.com", custom_domain = true }
]

