name = "meridian-ai-worker"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[env.production]
vars = { ENVIRONMENT = "production" }

[env.development]
vars = { ENVIRONMENT = "development" }

# Environment variables (set these using wrangler secret put)
# CLOUDFLARE_ACCOUNT_ID
# CLOUDFLARE_GATEWAY_ID  
# CLOUDFLARE_API_TOKEN
# OPENAI_API_KEY
# ANTHROPIC_API_KEY (optional)
# GOOGLE_API_KEY (optional)

