version: '3.8'

services:
  meridian-ml-service:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: meridian/ml-service:latest
    container_name: meridian-ml-service
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - API_TOKEN=${API_TOKEN:-your-secret-token-here}
      - EMBEDDING_MODEL_NAME=/home/appuser/app/models
      - PYTHONUNBUFFERED=1
    volumes:
      # Optional: Mount model cache for persistence
      - ./models:/home/appuser/app/models:ro
    networks:
      - meridian-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'

networks:
  meridian-network:
    driver: bridge

volumes:
  models:
    driver: local 