# fly.toml app configuration file generated for meridian-ml-service on 2025-04-25T16:34:14+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'meridian-ml-service'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

# Add a health check pointing to your root or ping endpoint
[[services.http_checks]]
   interval = "10s"
   timeout = "2s"
   grace_period = "5s" # Give it time to start, especially with model download
   method = "GET"
   path = "/ping" # or "/"
   protocol = "http"
   port = 8080

[[services.ports]]
    handlers = ["http"]
    port = 8080
    force_https = true  # optional