name = "meridian-frontend"
compatibility_date = "2025-04-30"
compatibility_flags = ["nodejs_compat"]

# 指定构建输出目录
pages_build_output_dir = "apps/frontend/dist"


# 生产环境变量
[env.production.vars]
DATABASE_URL = "postgresql://swj:npg_r2eJPYg6nQft@ep-crimson-hat-a16d92db-pooler.ap-southeast-1.aws.neon.tech/meridian?sslmode=require"
ADMIN_USERNAME = "admin@swj"
PUBLIC_WORKER_API = "https://meridian-backend.swj299792458.workers.dev"